CDNSTORES/Models/CDNSTORES/Color.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CDNSTORES.Models.CDNSTORES
{
    public class Color
    {
        [Key]
        [DisplayName("Mã màu :")]
        public int Id { get; set; }

        [Required(ErrorMessage = "Bạn cần nhập tên màu sắc!")]
        [DisplayName("Màu sắc :")]
        public string Name { get; set; }

        public ICollection<Product> Products { get; set; }
    }
}

CDNSTORES/Models/CDNSTORES/Material.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CDNSTORES.Models.CDNSTORES
{
    public class Material
    {
        [Key]
        [DisplayName("Mã chất liệu :")]
        public int Id { get; set; }

        [Required(ErrorMessage = "Bạn cần nhập tên chất liệu!")]
        [DisplayName("Chất liệu :")]
        public string Name { get; set; }

        public ICollection<Product> Products { get; set; }

    }
}

CDNSTORES/Areas/Admin/Controllers/ColorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CDNSTORES.Models;
using CDNSTORES.Models.CDNSTORES;

namespace CDNSTORES.Areas.Admin.Controllers
{
    public class ColorsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Admin/Colors
        public ActionResult Index()
        {
            return View(db.Colors.ToList());
        }

        // GET: Admin/Colors/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Color color = db.Colors.Find(id);
            if (color == null)
            {
                return HttpNotFound();
            }
            return View(color);
        }

        // GET: Admin/Colors/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/Colors/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name")] Color color)
        {
            if (ModelState.IsValid)
            {
                db.Colors.Add(color);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(color);
        }

        // GET: Admin/Colors/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Color color = db.Colors.Find(id);
            if (color == null)
            {
                return HttpNotFound();
            }
            return View(color);
        }

        // POST: Admin/Colors/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name")] Color color)
        {
            if (ModelState.IsValid)
            {
                db.Entry(color).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(color);
        }

        // GET: Admin/Colors/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Color color = db.Colors.Find(id);
            if (color == null)
            {
                return HttpNotFound();
            }
            return View(color);
        }

        // POST: Admin/Colors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Color color = db.Colors.Find(id);
            db.Colors.Remove(color);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CDNSTORES/Areas/Admin/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CDNSTORES.Models;
using CDNSTORES.Models.CDNSTORES;

namespace CDNSTORES.Areas.Admin.Controllers
{
    [Authorize]
    public class ProductsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Admin/Products
        public ActionResult Index()
        {
            var products = db.Products.Include(p => p.Color).Include(p => p.Images).Include(p => p.Material).Include(p => p.Price).Include(p => p.Status);
            return View(products.ToList());
        }

        // GET: Admin/Products/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            var colorofproduct = db.Colors.Find(product.ColorId);
            var imageofproduct = db.Images.Find(product.ImagesId);
            var materialofShow = db.Materials.Find(product.MaterialId);
            var priceofShow = db.Prices.Find(product.PriceId);
            var statusofShow = db.Statuses.Find(product.StatusId);
            product.Color = colorofproduct;
            product.Images = imageofproduct;
            product.Material = materialofShow;
            product.Price = priceofShow;
            product.Status = statusofShow;
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // GET: Admin/Products/Create
        public ActionResult Create()
        {
            ViewBag.ColorId = new SelectList(db.Colors, "Id", "Name");
            ViewBag.ImagesId = new SelectList(db.Images, "Id", "Picture1");
            ViewBag.MaterialId = new SelectList(db.Materials, "Id", "Name");
            ViewBag.PriceId = new SelectList(db.Prices, "Id", "Money");
            ViewBag.StatusId = new SelectList(db.Statuses, "Id", "Name");
            return View();
        }

        // POST: Admin/Products/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,ImagesId,ColorId,MaterialId,PriceId,StatusId")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Products.Add(product);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ColorId = new SelectList(db.Colors, "Id", "Name", product.ColorId);
            ViewBag.ImagesId = new SelectList(db.Images, "Id", "Picture1", product.ImagesId);
            ViewBag.MaterialId = new SelectList(db.Materials, "Id", "Name", product.MaterialId);
            ViewBag.PriceId = new SelectList(db.Prices, "Id", "Id", product.PriceId);
            ViewBag.StatusId = new SelectList(db.Statuses, "Id", "Name", product.StatusId);
            return View(product);
        }

        // GET: Admin/Products/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            ViewBag.ColorId = new SelectList(db.Colors, "Id", "Name", product.ColorId);
            ViewBag.ImagesId = new SelectList(db.Images, "Id", "Picture1", product.ImagesId);
            ViewBag.MaterialId = new SelectList(db.Materials, "Id", "Name", product.MaterialId);
            ViewBag.PriceId = new SelectList(db.Prices, "Id", "Money", product.PriceId);
            ViewBag.StatusId = new SelectList(db.Statuses, "Id", "Name", product.StatusId);
            return View(product);
        }

        // POST: Admin/Products/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,ImagesId,ColorId,MaterialId,PriceId,StatusId")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ColorId = new SelectList(db.Colors, "Id", "Name", product.ColorId);
            ViewBag.ImagesId = new SelectList(db.Images, "Id", "Picture1", product.ImagesId);
            ViewBag.MaterialId = new SelectList(db.Materials, "Id", "Name", product.MaterialId);
            ViewBag.PriceId = new SelectList(db.Prices, "Id", "Id", product.PriceId);
            ViewBag.StatusId = new SelectList(db.Statuses, "Id", "Name", product.StatusId);
            return View(product);
        }

        // GET: Admin/Products/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            var colorofproduct = db.Colors.Find(product.ColorId);
            var imageofproduct = db.Images.Find(product.ImagesId);
            var materialofShow = db.Materials.Find(product.MaterialId);
            var priceofShow = db.Prices.Find(product.PriceId);
            var statusofShow = db.Statuses.Find(product.StatusId);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Admin/Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Product product = db.Products.Find(id);
            db.Products.Remove(product);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CDNSTORES/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CDNSTORES.Models;
using CDNSTORES.Models.CDNSTORES;

namespace CDNSTORES.Controllers
{
    [Authorize]
    public class OrdersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Orders
        public ActionResult Index()
        {
            var orders = db.Orders.Include(o => o.Customer).Include(o => o.OrderInfo).Include(o => o.Product).Include(o => o.Size);
            return View(orders.ToList());
        }

        // GET: Orders/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Order order = db.Orders.Find(id);
            var nameorder = db.Users.Find(order.CustomerId);
            var diachiorder = db.OrderInfos.Find(order.OrderInfoId);
            var masanphamorder = db.Products.Find(order.ProductId);
            var kichcoorder = db.Sizes.Find(order.SizeId);
            order.Customer = nameorder;
            order.OrderInfo = diachiorder;
            order.Product = masanphamorder;
            order.Size = kichcoorder;
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // GET: Orders/Create
        public ActionResult Create()
        {
            ViewBag.CustomerId = new SelectList(db.Users, "Id", "Name");
            ViewBag.OrderInfoId = new SelectList(db.OrderInfos, "Id", "Place");
            ViewBag.ProductId = new SelectList(db.Products, "Id", "Id");
            ViewBag.SizeId = new SelectList(db.Sizes, "Id", "Name");
            return View();
        }
        

        // POST: Orders/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,SizeId,Number,CustomerId,OrderInfoId,ProductId")] Order order)
        {
            if (ModelState.IsValid)
            {
                db.Orders.Add(order);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CustomerId = new SelectList(db.Users, "Id", "Name", order.CustomerId);
            ViewBag.OrderInfoId = new SelectList(db.OrderInfos, "Id", "Name", order.OrderInfoId);
            ViewBag.ProductId = new SelectList(db.Products, "Id", "Name", order.ProductId);
            ViewBag.SizeId = new SelectList(db.Sizes, "Id", "Name", order.SizeId);
            return View(order);
        }

        // GET: Orders/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            ViewBag.CustomerId = new SelectList(db.Users, "Id", "Name", order.CustomerId);
            ViewBag.OrderInfoId = new SelectList(db.OrderInfos, "Id", "Place", order.OrderInfoId);
            ViewBag.ProductId = new SelectList(db.Products, "Id", "Id", order.ProductId);
            ViewBag.SizeId = new SelectList(db.Sizes, "Id", "Name", order.SizeId);
            return View(order);
        }

        // POST: Orders/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,SizeId,Number,CustomerId,OrderInfoId,ProductId")] Order order)
        {
            if (ModelState.IsValid)
            {
                db.Entry(order).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CustomerId = new SelectList(db.Users, "Id", "Name", order.CustomerId);
            ViewBag.OrderInfoId = new SelectList(db.OrderInfos, "Id", "Name", order.OrderInfoId);
            ViewBag.ProductId = new SelectList(db.Products, "Id", "Name", order.ProductId);
            ViewBag.SizeId = new SelectList(db.Sizes, "Id", "Name", order.SizeId);
            return View(order);
        }

        // GET: Orders/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            var nameorder = db.Users.Find(order.CustomerId);
            var masanphamorder = db.Products.Find(order.ProductId);
            var tensanphamorder = db.Products.Find(order.ProductId);
            var hinhsanpham = db.Images.Find(order.ProductId);
            var kichcoorder = db.Sizes.Find(order.SizeId);
            var giasanpham = db.Prices.Find(order.ProductId);
            var diachiorder = db.OrderInfos.Find(order.OrderInfoId);     
            order.Customer = nameorder;
            order.Product = masanphamorder;
            order.OrderInfo = diachiorder;           
            order.Size = kichcoorder;
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // POST: Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Order order = db.Orders.Find(id);
            db.Orders.Remove(order);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CDNSTORES/Views/Products/Color.cshtml
@model IEnumerable<CDNSTORES.Models.CDNSTORES.Product>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<br />
<img src="~/Content/images/desktop_productlist.jpg" alt="" class="desktop_productlist" />


<div class="home-product">
    <div class="row sm-gutter">


        @foreach (var item in Model)
        {

            <div class="col l-2-4 m-4 c-6">
                <div class="home-product-item">
                    <img src="/@Html.DisplayFor(modelItem=>item.Images.Picture1)" class="home-product-item__img" style="width:100%;" />
                    <h4 class="home-product-item__name_2 home-product-item__name_2_price">@Html.DisplayFor(modelItem => item.Status.Name)</h4>
                    <h4 class="home-product-item__name_2">@Html.DisplayFor(modelItem => item.Price.Money)</h4>
                    <h4 class="home-product-item__name_1">@Html.DisplayFor(modelItem => item.Name)</h4>
                    <h4 class="home-product-item__name_2" style="color:black;">@Html.ActionLink("Xem chi tiết", "Details", "Products", new { id = item.Id }, null)</h4>
                </div>
            </div>
        }

    </div>
</div>

<ul class="pagination home-product__pagination">
    <li class="pagination-item">
        <a href="" class="pagination-item__link">
            <i class="pagination-item__icon fas fa-angle-left"></i>
        </a>
    </li>
    <li class="pagination-item pagination-item--active">
        <a href="" class="pagination-item__link">1</a>
    </li>
    <li class="pagination-item">
        <a href="" class="pagination-item__link">2</a>
    </li>
    <li class="pagination-item">
        <a href="" class="pagination-item__link">3</a>
    </li>
    <li class="pagination-item">
        <a href="" class="pagination-item__link">4</a>
    </li>
    <li class="pagination-item">
        <a href="" class="pagination-item__link">5</a>
    </li>
    <li class="pagination-item">
        <a href="" class="pagination-item__link">...</a>
    </li>
    <li class="pagination-item">
        <a href="" class="pagination-item__link">14</a>
    </li>
    <li class="pagination-item">
        <a href="" class="pagination-item__link">
            <i class="pagination-item__icon fas fa-angle-right"></i>
        </a>
    </li>
</ul>
<script>
    $('#btnSearch').on('click', function () {
        //lay gia tri cua textbox
        var giatrinhap = $('#txtInput').val();
        //cho trinh duyet truy cap
        window.location.href = "/Products/SearchByName?name=" + giatrinhap;
    });
</script>

CDNSTORES/Views/Products/Details.cshtml
@model CDNSTORES.Models.CDNSTORES.Product

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<hr class="thanh-ngang" />
<div class="banner-bootom-w3-agileits">
    <div class="row sm-gutter details-container">
        <!-- tittle heading -->
        <h3 class="tittle-w3l">
            <span class="heading-style">
                <i></i>
                <i></i>
                <i></i>
            </span>
        </h3>
        <!-- //tittle heading -->
        <div class="col-md-7 single-right-left ">
            <div class="grid images_3_of_2">
                <div class="flexslider">
                    <ul class="slides" style="z-index: 1;">
                        <li data-thumb="~/@Html.DisplayFor(model => model.Images.Picture1)">
                            <div class="thumb-image">
                                <img src="~/@Html.DisplayFor(model => model.Images.Picture1)" class="detail-product-img1">
                            </div>
                        </li>
                        <li data-thumb="~/@Html.DisplayFor(model => model.Images.Picture2)">
                            <div class="thumb-image">
                                <img src="~/@Html.DisplayFor(model => model.Images.Picture2)" class="detail-product-img2">
                            </div>
                        </li>
                        <li data-thumb="~/@Html.DisplayFor(model => model.Images.Picture3)">
                            <div class="thumb-image">
                                <img src="~/@Html.DisplayFor(model => model.Images.Picture3)" class="detail-product-img3">
                            </div>
                        </li>
                        <li data-thumb="~/@Html.DisplayFor(model => model.Images.Picture4)">
                            <div class="thumb-image">
                                <img src="~/@Html.DisplayFor(model => model.Images.Picture4)" class="detail-product-img2">
                            </div>
                        </li>
                        <li data-thumb="~/@Html.DisplayFor(model => model.Images.Picture5)">
                            <div class="thumb-image">
                                <img src="~/@Html.DisplayFor(model => model.Images.Picture5)" class="detail-product-img3">
                            </div>
                        </li>
                        <li data-thumb="~/@Html.DisplayFor(model => model.Images.Picture6)">
                            <div class="thumb-image">
                                <img src="~/@Html.DisplayFor(model => model.Images.Picture6)" class="detail-product-img2">
                            </div>
                        </li>
                        <li data-thumb="~/@Html.DisplayFor(model => model.Images.Picture7)">
                            <div class="thumb-image">
                                <img src="~/@Html.DisplayFor(model => model.Images.Picture7)" class="detail-product-img3">
                            </div>
                        </li>
                    </ul>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
        <div class="col-md-5 single-right-left simpleCart_shelfItem">
            <h4 class="detail-product-name">  @Html.DisplayFor(model => model.Name) </h4>
            <div class="detail-product-info">
                <div class="detail-product-info-id">
                    Mã sản phẩm:<strong> @Html.DisplayFor(model => model.Id)</strong>
                </div>
                <div class="detail-product-info-status">
                    Tình trạng: <strong> @Html.DisplayFor(model => model.Status.Name)</strong>
                </div>
            </div>
            <div class="detail-product-price">
                @Html.DisplayFor(model => model.Price.Money) VNĐ
            </div>
            <div class="detail-dathang">
                <div class="hand-left">
                    
                </div>
                <div class="detail-order">
                    @Html.ActionLink("Đặt hàng ngay", "Create", "Orders")
                </div>
                <div class="hand-right">
                   
                </div>
            </div>
            <hr style="border: 1px dashed black;" />

            <h4 class="detail-product-name">THÔNG TIN SẢN PHẨM</h4>
            <p class="detail-product-info4">Gender: Unisex</p>
            <p class="detail-product-info4">Size run: 35 – 46</p>
            <p class="detail-product-info4">Upper: Canvas NE</p>
            <p class="detail-product-info4">Gender: Unisex</p>
            <hr style="border: 1px dashed black;" />

            <p class="detail-product-info4" style="font-size:32px;margin:10px 0;">SIZE CHARE</p>
            <img src="~/Content/assets/img/Size-chart-1.jpg" alt="" class="img-size-char" />
            <hr style="border: 1px dashed black;" />

            <h4 class="detail-product-name">QUY ĐỊNH ĐỔI TRẢ</h4>
            <ul>
                <li>Chỉ đổi hàng 1 lần duy nhất, mong bạn cân nhắc kĩ trước khi quyết định.</li>
                <li>Thời hạn đổi sản phẩm khi mua trực tiếp tại cửa hàng là 07 ngày, kể từ ngày mua. Đổi sản phẩm khi mua online là 14 ngày, kể từ ngày nhận hàng.</li>
                <li>Sản phẩm đổi phải kèm hóa đơn. Bắt buộc phải còn nguyên tem, hộp, nhãn mác.</li>
                <li>Sản phẩm đổi không có dấu hiệu đã qua sử dụng, không giặt tẩy, bám bẩn, biến dạng.</li>
                <li>Trong trường hợp sản phẩm - size bạn muốn đổi không còn hàng trong hệ thống. Vui lòng chọn sản phẩm khác.</li>
                <li>Không hoàn trả bằng tiền mặt dù bất cứ trong trường hợp nào. Mong bạn thông cảm.</li>
            </ul>
        </div>
        
    </div>
</div>
<hr />

@section Scripts {
    @Scripts.Render("~/bundles/shop_detail")
    <script>
        // Can also be used with $(document).ready()
        $(window).load(function () {
            $('.flexslider').flexslider({
                animation: "slide",
                controlNav: "thumbnails"
            });
        });
    </script>
    <script>
        $(window).load(function () {
            $("#flexiselDemo1").flexisel({
                visibleItems: 3,
                animationSpeed: 1000,
                autoPlay: true,
                autoPlaySpeed: 3000,
                pauseOnHover: true,
                enableResponsiveBreakpoints: true,
                responsiveBreakpoints: {
                    portrait: {
                        changePoint: 480,
                        visibleItems: 1
                    },
                    landscape: {
                        changePoint: 640,
                        visibleItems: 2
                    },
                    tablet: {
                        changePoint: 768,
                        visibleItems: 2
                    }
                }
            });

        });
    </script>

}

CDNSTORES/Views/Products/GetProductByMaterial.cshtml
@model IEnumerable<CDNSTORES.Models.CDNSTORES.Product>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<br />
<img src="~/Content/images/desktop_productlist.jpg" alt="" class="desktop_productlist" />


<div class="home-product">
    <div class="row sm-gutter">


        @foreach (var item in Model)
        {

            <div class="col l-2-4 m-4 c-6">
                <div class="home-product-item">
                    <img src="/@Html.DisplayFor(modelItem=>item.Images.Picture1)" class="home-product-item__img" style="width:100%;" />
                    <h4 class="home-product-item__name_2 home-product-item__name_2_price">@Html.DisplayFor(modelItem => item.Status.Name)</h4>
                    <h4 class="home-product-item__name_2">@Html.DisplayFor(modelItem => item.Price.Money)</h4>
                    <h4 class="home-product-item__name_1">@Html.DisplayFor(modelItem => item.Name)</h4>
                    <h4 class="home-product-item__name_2" style="color:black;">@Html.ActionLink("Xem chi tiết", "Details", "Products", new { id = item.Id }, null)</h4>
                </div>
            </div>
        }

    </div>
</div>

<ul class="pagination home-product__pagination">
    <li class="pagination-item">
        <a href="" class="pagination-item__link">
            <i class="pagination-item__icon fas fa-angle-left"></i>
        </a>
    </li>
    <li class="pagination-item pagination-item--active">
        <a href="" class="pagination-item__link">1</a>
    </li>
    <li class="pagination-item">
        <a href="" class="pagination-item__link">2</a>
    </li>
    <li class="pagination-item">
        <a href="" class="pagination-item__link">3</a>
    </li>
    <li class="pagination-item">
        <a href="" class="pagination-item__link">4</a>
    </li>
    <li class="pagination-item">
        <a href="" class="pagination-item__link">5</a>
    </li>
    <li class="pagination-item">
        <a href="" class="pagination-item__link">...</a>
    </li>
    <li class="pagination-item">
        <a href="" class="pagination-item__link">14</a>
    </li>
    <li class="pagination-item">
        <a href="" class="pagination-item__link">
            <i class="pagination-item__icon fas fa-angle-right"></i>
        </a>
    </li>
</ul>
<script>
    $('#btnSearch').on('click', function () {
        //lay gia tri cua textbox
        var giatrinhap = $('#txtInput').val();
        //cho trinh duyet truy cap
        window.location.href = "/Products/SearchByName?name=" + giatrinhap;
    });
</script>

CDNSTORES/Views/Products/SearchByName.cshtml
@model List<CDNSTORES.Models.CDNSTORES.Product>
@{
    ViewBag.Title = "SearchByName";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (Model.Count > 0)
{
    <h5>Số sản phẩm tìm được khớp với từ khóa @ViewBag.key là :@Model.Count </h5>
        <div class="home-product">
            <div class="row sm-gutter">
    @foreach (var item in Model)
    {
                <div class="col l-2-4 m-4 c-6">
                    <div class="home-product-item">
                        <img src="~/@Html.DisplayFor(modelItem => item.Images.Picture1)" class="home-product-item__img" style="width:100px;" alt="Ảnh sản phẩm" />
                        <h4 class="home-product-item__name_2 home-product-item__name_2_price">@Html.DisplayFor(modelItem => item.Status.Name)</h4>
                        <h4 class="home-product-item__name_2">@Html.DisplayFor(modelItem => item.Price.Money)</h4>
                        <h4 class="home-product-item__name_1">@Html.DisplayFor(modelItem => item.Name)</h4>
                        <h4 class="home-product-item__name_2" style="color:black;">@Html.ActionLink("Xem chi tiết", "Details", "Products", new { id = item.Id }, null)</h4>
                    </div>
                </div>
    }
            </div>
        </div>
}
else
{
    <h2>Không có sản phẩm nào phù hợp với từ khóa @ViewBag.key </h2>
}